apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: job
          image: job-image
          envFrom:
            - configMapRef:
                name: job-config
