apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: credentials
spec:
  mount: secret
  type: kv-v2
  refreshAfter: 1h
  destination:
    create: true
    transformation:
      excludeRaw: true
