apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ghcr-pull-credentials
spec:
  mount: secret
  type: kv-v2
  path: ghcr/openhorizontal/pull
  refreshAfter: 1h
  destination:
    name: openhorizontal-ghcr-pull-credentials
    create: true
    type: kubernetes.io/dockerconfigjson
    transformation:
      excludeRaw: true
