apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
spec:
  vaultAuthGlobalRef:
    allowDefault: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: credentials
spec:
  mount: secret
  type: kv-v2
  refreshAfter: 1h
  destination:
    create: true
    transformation:
      excludeRaw: true
